name: hw1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - libsodium=1.0.16=h14c3975_1001
  - openssl=1.1.1a=h14c3975_1000
  - pyzmq=17.1.2=py36h6afc9c9_1001
  - requests=2.13.0=py36_0
  - torchfile=0.1.0=py_0
  - tornado=5.1.1=py36h14c3975_1000
  - tqdm=4.31.1=py_0
  - visdom=0.1.8.8=0
  - websocket-client=0.54.0=py36_1000
  - zeromq=4.2.5=hf484d3e_1006
  - blas=1.0=mkl
  - cffi=1.11.5=py36he75722e_1
  - cudatoolkit=9.0=h13b8566_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.1=py36_0
  - pycparser=2.19=py36_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - scipy=1.2.0=py36h7c811a0_0
  - setuptools=40.7.3=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.0.1=py3.6_cuda9.0.176_cudnn7.4.2_2
  - torchvision=0.2.1=py_2
prefix: /home/timy90022/anaconda3/envs/cvfx

